//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCENUMERATION
    {
        public CCENUMERATION()
        {
            this.CCACTIONMAPs = new HashSet<CCACTIONMAP>();
            this.CCMEMOLOGs = new HashSet<CCMEMOLOG>();
            this.CCMEMOMASTERs = new HashSet<CCMEMOMASTER>();
            this.CCMEMOMASTERs1 = new HashSet<CCMEMOMASTER>();
            this.CCMEMOMASTERs2 = new HashSet<CCMEMOMASTER>();
            this.CCMEMOMASTERs3 = new HashSet<CCMEMOMASTER>();
            this.CCMEMOMASTERs4 = new HashSet<CCMEMOMASTER>();
            this.CCACTIONGROUPMAPs = new HashSet<CCACTIONGROUPMAP>();
        }
    
        public long ID { get; set; }
        public int TYPE { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string NAMEVALUE { get; set; }
        public bool ISACTIVE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    
        public virtual ICollection<CCACTIONMAP> CCACTIONMAPs { get; set; }
        public virtual ICollection<CCMEMOLOG> CCMEMOLOGs { get; set; }
        public virtual ICollection<CCMEMOMASTER> CCMEMOMASTERs { get; set; }
        public virtual ICollection<CCMEMOMASTER> CCMEMOMASTERs1 { get; set; }
        public virtual ICollection<CCMEMOMASTER> CCMEMOMASTERs2 { get; set; }
        public virtual ICollection<CCMEMOMASTER> CCMEMOMASTERs3 { get; set; }
        public virtual ICollection<CCMEMOMASTER> CCMEMOMASTERs4 { get; set; }
        public virtual ICollection<CCACTIONGROUPMAP> CCACTIONGROUPMAPs { get; set; }
    }
}
