//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCEVENTLOG
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public string IPAddress { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
    }
}
