//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMEMOATTACHMENT
    {
        public long ID { get; set; }
        public long MEMOMASTERID { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
    
        public virtual CCMEMOMASTER CCMEMOMASTER { get; set; }
        public virtual CCUSER CCUSER { get; set; }
    }
}
