//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMEMOLOG
    {
        public long ID { get; set; }
        public long MEMOMASTERID { get; set; }
        public long ASSIGNGROUP { get; set; }
        public string ACTIONDETAILS { get; set; }
        public long ACTIONTYPE { get; set; }
        public Nullable<long> ACTEDBY { get; set; }
        public string REMARKS { get; set; }
        public bool ISACTIVE { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
    
        public virtual CCENUMERATION CCENUMERATION { get; set; }
        public virtual CCGROUP CCGROUP { get; set; }
        public virtual CCMEMOMASTER CCMEMOMASTER { get; set; }
        public virtual CCUSER CCUSER { get; set; }
    }
}
