//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
using OBLContactCenter.Models.MetaModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

[MetadataType(typeof(CCROLEMeta))]
    
    public partial class CCROLE
    {
        public CCROLE()
        {
            this.CCACTIONMAPs = new HashSet<CCACTIONMAP>();
            this.CCROLEMENUs = new HashSet<CCROLEMENU>();
            this.CCUSERs = new HashSet<CCUSER>();
            this.CCACTIONGROUPMAPs = new HashSet<CCACTIONGROUPMAP>();
        }
    
        public long ID { get; set; }
        public string ROLENAME { get; set; }
        public bool ISADMIN { get; set; }
        public bool ISACTIVE { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
    
        public virtual ICollection<CCACTIONMAP> CCACTIONMAPs { get; set; }
        public virtual ICollection<CCROLEMENU> CCROLEMENUs { get; set; }
        public virtual ICollection<CCUSER> CCUSERs { get; set; }
        public virtual ICollection<CCACTIONGROUPMAP> CCACTIONGROUPMAPs { get; set; }
    }
}
