//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBLContactCenter.EFnClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCROLEMENU
    {
        public long ID { get; set; }
        public long ROLEID { get; set; }
        public long MENUID { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
    
        public virtual CCMENU CCMENU { get; set; }
        public virtual CCROLE CCROLE { get; set; }
    }
}
